In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('owid-co2-data.csv')
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,...,NaN,0.106,0.001,0.001,0.002,0.0,34.348,17.531,-0.027,-0.261
50187,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,...,NaN,0.105,0.001,0.001,0.002,0.0,31.323,15.775,0.612,7.209
50188,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,...,NaN,0.104,0.001,0.001,0.002,0.0,33.549,17.599,0.539,5.280
50189,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,...,NaN,0.103,0.001,0.001,0.002,0.0,33.772,17.910,0.315,3.018
50190,Zimbabwe,2023,ZWE,16340829.0,NaN,0.531,0.032,11.164,0.739,7.090,...,NaN,0.102,0.001,0.001,0.002,0.0,33.955,18.608,NaN,NaN

In [4]:
threshold = 0.6  # 60% threshold for missing values
min_non_null_count = int((1 - threshold) * len(df))
df_cleaned = df.dropna(axis=1, thresh=min_non_null_count)
df_cleaned

,country,year,iso_code,population,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,...,share_global_cumulative_oil_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
0,Afghanistan,1750,AFG,2802560.0,0.000,0.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,0.473,0.031,10.263,-0.942,-8.411,19.807,...,0.025,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
50187,Zimbabwe,2020,ZWE,15526888.0,0.496,0.032,8.495,-1.768,-17.231,17.430,...,0.025,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
50188,Zimbabwe,2021,ZWE,15797220.0,0.531,0.034,10.204,1.709,20.120,18.752,...,0.025,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
50189,Zimbabwe,2022,ZWE,16069061.0,0.531,0.033,10.425,0.221,2.169,18.447,...,0.025,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
50190,Zimbabwe,2023,ZWE,16340829.0,0.531,0.032,11.164,0.739,7.090,18.567,...,0.025,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [5]:
essential_columns = ['country', 'year', 'population', 'co2']
df_cleaned = df_cleaned.dropna(subset=essential_columns)
df_cleaned

,country,year,iso_code,population,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,...,share_global_cumulative_oil_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
199,Afghanistan,1949,AFG,7356890.0,0.000,0.000,0.015,NaN,NaN,6.250,...,0.000,0.114,0.000,0.128,0.000,0.000,0.001,0.0,18.288,1.297
200,Afghanistan,1950,AFG,7776182.0,0.000,0.000,0.084,0.070,475.000,7.316,...,0.000,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
201,Afghanistan,1951,AFG,7879343.0,0.000,0.000,0.092,0.007,8.696,8.264,...,0.000,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
202,Afghanistan,1952,AFG,7987783.0,0.000,0.000,0.092,0.000,0.000,9.192,...,0.001,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
203,Afghanistan,1953,AFG,8096703.0,0.000,0.000,0.106,0.015,16.000,10.269,...,0.001,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,0.473,0.031,10.263,-0.942,-8.411,19.807,...,0.025,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
50187,Zimbabwe,2020,ZWE,15526888.0,0.496,0.032,8.495,-1.768,-17.231,17.430,...,0.025,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
50188,Zimbabwe,2021,ZWE,15797220.0,0.531,0.034,10.204,1.709,20.120,18.752,...,0.025,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
50189,Zimbabwe,2022,ZWE,16069061.0,0.531,0.033,10.425,0.221,2.169,18.447,...,0.025,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
50190,Zimbabwe,2023,ZWE,16340829.0,0.531,0.032,11.164,0.739,7.090,18.567,...,0.025,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [6]:
df_cleaned = df_cleaned.drop_duplicates()
df_cleaned

,country,year,iso_code,population,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,...,share_global_cumulative_oil_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
199,Afghanistan,1949,AFG,7356890.0,0.000,0.000,0.015,NaN,NaN,6.250,...,0.000,0.114,0.000,0.128,0.000,0.000,0.001,0.0,18.288,1.297
200,Afghanistan,1950,AFG,7776182.0,0.000,0.000,0.084,0.070,475.000,7.316,...,0.000,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
201,Afghanistan,1951,AFG,7879343.0,0.000,0.000,0.092,0.007,8.696,8.264,...,0.000,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
202,Afghanistan,1952,AFG,7987783.0,0.000,0.000,0.092,0.000,0.000,9.192,...,0.001,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
203,Afghanistan,1953,AFG,8096703.0,0.000,0.000,0.106,0.015,16.000,10.269,...,0.001,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50186,Zimbabwe,2019,ZWE,15271377.0,0.473,0.031,10.263,-0.942,-8.411,19.807,...,0.025,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
50187,Zimbabwe,2020,ZWE,15526888.0,0.496,0.032,8.495,-1.768,-17.231,17.430,...,0.025,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
50188,Zimbabwe,2021,ZWE,15797220.0,0.531,0.034,10.204,1.709,20.120,18.752,...,0.025,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
50189,Zimbabwe,2022,ZWE,16069061.0,0.531,0.033,10.425,0.221,2.169,18.447,...,0.025,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
50190,Zimbabwe,2023,ZWE,16340829.0,0.531,0.032,11.164,0.739,7.090,18.567,...,0.025,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [7]:
df_cleaned.to_csv("owid-co2-data-cleaned.csv", index=False)